Fix missing environ with darwin g++
misc.d: In function 'Values C_get_env()':
misc.d:215:16: error: 'environ' was not declared in this scope
     for (epp = environ; *epp; epp++, count++) push_envar(*epp);

https://sourceforge.net/p/clisp/patches/49/