win32: add -I. for include w32shell.c
gcc does not have -I. as default.
clisp.c:2191:23: fatal error: w32shell.c: No such file or directory
 # include <w32shell.c>