add appveyor smokers
on my rurban account still, but can be easily transferred
to an official github bridge.

add utils/libffcall-1.13-20170225-funbegin.patch:
the released libffcall and this beta are broken. patch it.
error: pasting formed '__builtin_avcall:', an invalid preprocessing token
FUNBEGIN(__builtin_avcall)

the patch only works on darwin, not on mingw yet.

add utils/libsigsegv-win64.patch from
https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-mingw-w64-libsigsegv-git/

appveyor: switch to i686-w64-mingw32

win64: update libsigsegv-win64 and libffcall patches

libsigsegv on win64 only fails on stackoverflow detection, but
does handle normal out of memory signals, which we need for the GC.

libffcall cpp pasting name##: does not work with gcc.